"""empty message

Revision ID: 092418c0e1fd
Revises: f4cd9a88f321
Create Date: 2022-08-21 10:47:23.057828

"""
from alembic import op
import sqlalchemy as sa

# (help: https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix)
# (help: https://stackoverflow.com/a/34294464)
import backend

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '092418c0e1fd'
down_revision = 'f4cd9a88f321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('uuid', backend.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('receive_time', sa.DateTime(), nullable=True),
    sa.Column('clear_time', sa.DateTime(), nullable=True),
    sa.Column('action', sa.Enum('accept', 'reject', 'idle', name='action'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarms'))
    )
    op.create_index(op.f('ix_alarms_date'), 'alarms', ['date'], unique=False)
    op.create_index(op.f('ix_alarms_uuid'), 'alarms', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarms_uuid'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_date'), table_name='alarms')
    op.drop_table('alarms')
    # ### end Alembic commands ###
