"""empty message

Revision ID: 2d058eb2d2a8
Revises: c20e50b530af
Create Date: 2023-02-18 10:32:00.650207

"""
from alembic import op
import sqlalchemy as sa

# (help: https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix)
# (help: https://stackoverflow.com/a/34294464)
import backend



# revision identifiers, used by Alembic.
revision = '2d058eb2d2a8'
down_revision = 'c20e50b530af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_load_datetime', table_name='load')
    op.drop_index('ix_manual_load_datetime', table_name='manual_load')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_manual_load_datetime', 'manual_load', ['datetime'], unique=False)
    op.create_index('ix_load_datetime', 'load', ['datetime'], unique=False)
    # ### end Alembic commands ###
