"""empty message

Revision ID: 51291767c175
Revises: 2d058eb2d2a8
Create Date: 2023-02-19 13:23:20.467247

"""
from alembic import op
import sqlalchemy as sa

# (help: https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix)
# (help: https://stackoverflow.com/a/34294464)
import backend



# revision identifiers, used by Alembic.
revision = '51291767c175'
down_revision = '2d058eb2d2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('program_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_alarms_program_id_program'), 'alarms', 'program', ['program_id'], ['id'])
    op.drop_column('alarms', 'program_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('program_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_alarms_program_id_program'), 'alarms', type_='foreignkey')
    op.drop_column('alarms', 'program_id')
    # ### end Alembic commands ###
