"""empty message

Revision ID: 744cc6f867a8
Revises: 7dd9d2ba0a2a
Create Date: 2022-10-04 14:28:21.478720

"""
from alembic import op
import sqlalchemy as sa

# (help: https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix)
# (help: https://stackoverflow.com/a/34294464)
import backend

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '744cc6f867a8'
down_revision = '7dd9d2ba0a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('uuid', backend.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load'))
    )
    op.create_index(op.f('ix_load_datetime'), 'load', ['datetime'], unique=True)
    op.create_index(op.f('ix_load_uuid'), 'load', ['uuid'], unique=False)
    op.create_table('manual_load',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('uuid', backend.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_load'))
    )
    op.create_index(op.f('ix_manual_load_datetime'), 'manual_load', ['datetime'], unique=True)
    op.create_index(op.f('ix_manual_load_uuid'), 'manual_load', ['uuid'], unique=False)
    op.drop_index('ix_loads_datetime', table_name='loads')
    op.drop_index('ix_loads_uuid', table_name='loads')
    op.drop_table('loads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_loads')
    )
    op.create_index('ix_loads_uuid', 'loads', ['uuid'], unique=False)
    op.create_index('ix_loads_datetime', 'loads', ['datetime'], unique=False)
    op.drop_index(op.f('ix_manual_load_uuid'), table_name='manual_load')
    op.drop_index(op.f('ix_manual_load_datetime'), table_name='manual_load')
    op.drop_table('manual_load')
    op.drop_index(op.f('ix_load_uuid'), table_name='load')
    op.drop_index(op.f('ix_load_datetime'), table_name='load')
    op.drop_table('load')
    # ### end Alembic commands ###
