"""empty message

Revision ID: 7dd9d2ba0a2a
Revises: 4d500ac9f418
Create Date: 2022-09-13 09:00:11.543165

"""
from alembic import op
import sqlalchemy as sa

# (help: https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix)
# (help: https://stackoverflow.com/a/34294464)
import backend

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dd9d2ba0a2a'
down_revision = '4d500ac9f418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activations', 'last_update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activations', sa.Column('last_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
