"""empty message

Revision ID: babb945acc6a
Revises: 51291767c175
Create Date: 2023-02-27 14:52:27.764202

"""
from alembic import op
import sqlalchemy as sa

# (help: https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix)
# (help: https://stackoverflow.com/a/34294464)
import backend



# revision identifiers, used by Alembic.
revision = 'babb945acc6a'
down_revision = '51291767c175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery', sa.Column('first_charging_start_time', sa.Integer(), nullable=False))
    op.add_column('battery', sa.Column('first_charging_end_time', sa.Integer(), nullable=False))
    op.add_column('battery', sa.Column('second_charging_start_time', sa.Integer(), nullable=False))
    op.add_column('battery', sa.Column('second_charging_end_time', sa.Integer(), nullable=False))
    op.drop_column('battery', 'second_end_time')
    op.drop_column('battery', 'second_start_time')
    op.drop_column('battery', 'first_start_time')
    op.drop_column('battery', 'first_end_time')
    op.drop_index('ix_results_datetime', table_name='results')
    op.create_unique_constraint(op.f('uq_results_datetime'), 'results', ['datetime', 'battery_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_results_datetime'), 'results', type_='unique')
    op.create_index('ix_results_datetime', 'results', ['datetime'], unique=False)
    op.add_column('battery', sa.Column('first_end_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('battery', sa.Column('first_start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('battery', sa.Column('second_start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('battery', sa.Column('second_end_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('battery', 'second_charging_end_time')
    op.drop_column('battery', 'second_charging_start_time')
    op.drop_column('battery', 'first_charging_end_time')
    op.drop_column('battery', 'first_charging_start_time')
    # ### end Alembic commands ###
