"""empty message

Revision ID: c20e50b530af
Revises: 7fb75948ac83
Create Date: 2023-02-13 02:25:50.980199

"""
from alembic import op
import sqlalchemy as sa

# (help: https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix)
# (help: https://stackoverflow.com/a/34294464)
import backend



# revision identifiers, used by Alembic.
revision = 'c20e50b530af'
down_revision = '7fb75948ac83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery', sa.Column('first_start_time', sa.Integer(), nullable=False))
    op.add_column('battery', sa.Column('first_end_time', sa.Integer(), nullable=False))
    op.add_column('battery', sa.Column('second_start_time', sa.Integer(), nullable=False))
    op.add_column('battery', sa.Column('second_end_time', sa.Integer(), nullable=False))
    op.drop_column('battery', 'night_start_time')
    op.drop_column('battery', 'morning_start_time')
    op.drop_column('battery', 'morning_end_time')
    op.drop_column('battery', 'night_end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery', sa.Column('night_end_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('battery', sa.Column('morning_end_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('battery', sa.Column('morning_start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('battery', sa.Column('night_start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('battery', 'second_end_time')
    op.drop_column('battery', 'second_start_time')
    op.drop_column('battery', 'first_end_time')
    op.drop_column('battery', 'first_start_time')
    # ### end Alembic commands ###
