"""empty message

Revision ID: f36f10d9bf9c
Revises: f57bcc749e41
Create Date: 2022-07-24 14:13:42.978697

"""
from alembic import op
import sqlalchemy as sa

# (help: https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix)
# (help: https://stackoverflow.com/a/34294464)
import backend



# revision identifiers, used by Alembic.
revision = 'f36f10d9bf9c'
down_revision = 'f57bcc749e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_activations_date'), 'activations', ['date', 'name'])
    op.drop_index('ix_loads_datetime', table_name='loads')
    op.create_index(op.f('ix_loads_datetime'), 'loads', ['datetime'], unique=True)
    op.drop_index('ix_results_datetime', table_name='results')
    op.create_index(op.f('ix_results_datetime'), 'results', ['datetime'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_datetime'), table_name='results')
    op.create_index('ix_results_datetime', 'results', ['datetime'], unique=False)
    op.drop_index(op.f('ix_loads_datetime'), table_name='loads')
    op.create_index('ix_loads_datetime', 'loads', ['datetime'], unique=False)
    op.drop_constraint(op.f('uq_activations_date'), 'activations', type_='unique')
    # ### end Alembic commands ###
